spring.application.name=psitaland
spring.datasource.url=jdbc:postgresql://db.bqpmicshzrykvxabphsd.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=${SUPABASE_PWD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect